#notes dynamo db table
notesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: notes
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: notesId
        AttributeType: S
    KeySchema:
      - AttributeName: notesId
        KeyType: HASH

#Cognito User Pool
cognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: serverless-course-dev-local-with-iac

#UserPoolWebClient
userPoolWebClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    UserPoolId: !Ref cognitoUserPool
    ClientName: web
    AllowedOAuthFlowsUserPoolClient: true
    AllowedOAuthScopes:
      - phone
      - email
      - profile
      - openid
    AllowedOAuthFlows:
      - implicit
    CallbackURLs:
      - http://localhost:3000
    SupportedIdentityProviders:
      - COGNITO

#UserPoolDomain
userPoolDomain:
  Type: AWS::Cognito::UserPoolDomain
  Properties:
    UserPoolId: !Ref cognitoUserPool
    Domain: serverless-course-dev-local-with-iac

#Application Parameter
userPoolIdParam:
  Type: AWS::SSM::Parameter
  Properties:
    Name: /notes/dev/userPoolId
    Type: String
    Value: !GetAtt cognitoUserPool.Arn
